### ISSUE TITLE
Unable to start app server

### ISSUE THREAD

**Issue by andreasindahl** [nekosaur/mashup#8]
```
Error: Cannot find module '../config/github.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/andreas/node/mashup/api/common/passport.js:3:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by nekosaur** [comment]
Resolved in #6
